package com.ccee.videotool.model.dbdao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ccee.videotool.model.db.DBVideo;

import com.ccee.videotool.model.dbdao.DBVideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBVideoDaoConfig;

    private final DBVideoDao dBVideoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBVideoDaoConfig = daoConfigMap.get(DBVideoDao.class).clone();
        dBVideoDaoConfig.initIdentityScope(type);

        dBVideoDao = new DBVideoDao(dBVideoDaoConfig, this);

        registerDao(DBVideo.class, dBVideoDao);
    }
    
    public void clear() {
        dBVideoDaoConfig.clearIdentityScope();
    }

    public DBVideoDao getDBVideoDao() {
        return dBVideoDao;
    }

}
